In [4]:
import pandas as pd
import matplotlib as plt
import sklearn
df=pd.read_csv('salaries.csv')
df.head()

  company                  job     degree  salary_more_then_100k
0  google      sales executive  bachelors                      0
1  google      sales executive    masters                      0
2  google     business manager  bachelors                      1
3  google     business manager    masters                      1
4  google  computer programmer  bachelors                      0

In [8]:
df.keys()
#  same as df.cloumns

Index(['company', 'job', 'degree', 'salary_more_then_100k'], dtype='object')

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 4 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   company                16 non-null     object
 1   job                    16 non-null     object
 2   degree                 16 non-null     object
 3   salary_more_then_100k  16 non-null     int64
dtypes: int64(1), object(3)
memory usage: 644.0+ bytes

In [14]:
# first we need to convert company degree and job columns into numerical 
from sklearn.preprocessing import LabelEncoder
e=LabelEncoder()
df["e_Company"]=e.fit_transform(df['company'])
df["e_job"]=e.fit_transform(df['job'])
df["e_degree"]=e.fit_transform(df['degree'])

In [15]:
df.head()

,company,job,degree,salary_more_then_100k,e_Company,e_job,e_degree
0,google,sales executive,bachelors,0,2,2,0
1,google,sales executive,masters,0,2,2,1
2,google,business manager,bachelors,1,2,0,0
3,google,business manager,masters,1,2,0,1
4,google,computer programmer,bachelors,0,2,1,0

In [21]:
df=df.drop(['company','job','degree'],axis='columns')

In [23]:
df.head()

   salary_more_then_100k  e_Company  e_job  e_degree
0                      0          2      2         0
1                      0          2      2         1
2                      1          2      0         0
3                      1          2      0         1
4                      0          2      1         0

In [26]:
X=df.drop('salary_more_then_100k',axis='columns')
y=df["salary_more_then_100k"]
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)
X_train.shape

(12, 3)

In [41]:
from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier(max_depth=3)
model.fit(X_train,y_train)
model.score(X_test,y_test)

0.75

In [42]:
pred=model.predict(X_test)
from sklearn.metrics import accuracy_score
accuracy_score(pred,y_test)

0.75